In [1]:
# 1.Import all the required Python Libraries.
import pandas as pd

In [3]:
# 2.Locate an open source data from the web (e.g., https://www.kaggle.com). Provide a clear description of the data and its source (i.e., URL of the web site).
df = pd.read_csv("C:\\Users\\LOQ\\Downloads\\Iris.csv")

In [5]:
# 3.Load the Dataset into pandas dataframe.
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1.0,5.1,3.5,1.4,0.2,Iris-setosa
1,2.0,4.9,3.0,1.4,0.2,Iris-setosa
2,NaN,4.7,3.2,1.3,0.2,Iris-setosa
3,NaN,4.6,3.1,1.5,0.2,Iris-setosa
4,NaN,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,3.0,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,5.0,1.9,Iris-virginica
147,148.0,6.5,3.0,5.2,2.0,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
# 4.Data Preprocessing: check for missing values in the data using pandas isnull(), describe() function to get some initial statistics.
#Provide variable descriptions. Types of variables etc. Check the dimensions of the data frame.

In [7]:
df.isnull()

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2     True          False         False          False         False    False
3     True          False         False          False         False    False
4     True          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [8]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  144.000000     150.000000    150.000000     150.000000    150.000000
mean    78.416667       5.843333      3.054000       3.758667      1.198667
std     41.861827       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     42.750000       5.100000      2.800000       1.600000      0.300000
50%     78.500000       5.800000      3.000000       4.350000      1.300000
75%    114.250000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [9]:
df.isnull().sum()

Id               6
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [11]:
df.size

900

In [13]:
df.shape

(150, 6)

In [16]:
# 5.Data Formatting and Data Normalization: Summarize the types of variables by checking the data types
#(i.e., character, numeric, integer, factor, and logical) of the variables in the data set.
#If variables are not in the correct data type, apply proper type conversions.

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             144 non-null    float64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(5), object(1)
memory usage: 7.2+ KB

In [22]:
db = df.dropna()

In [26]:
# Data Formatiing
db["Id"].astype(int)

0        1
1        2
8        9
9       10
10      11
      ...
145    146
146    147
147    148
148    149
149    150
Name: Id, Length: 144, dtype: int64

In [27]:
# 6.Turn categorical variables into quantitative variables in Python. In addition to the codes and outputs,
#explain every operation that you do in the above steps and explain everything that you do to import/read/scrape the data set.

In [28]:
db["Species"] = db["Species"].replace({"Iris-setosa":0,"Iris-virginica":1})

0      0
1      0
8      0
9      0
10     0
      ..
145    1
146    1
147    1
148    1
149    1
Name: Species, Length: 144, dtype: object