Problem Statement: Group-A/Q3.ipynb

Descriptive Statistics - Measures of Central Tendency and variability Perform the following operations on any open source dataset (e.g., data.csv)

1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for a dataset (age, income etc.) with numeric variables grouped by one of the qualitative (categorical) variable. For example, if your categorical variable is age groups and quantitative variable is income, then provide summary statistics of income grouped by the age groups. Create a list that contains a numeric value for each response to the categorical variable.
2. Write a Python program to display some basic statistical details like percentile, mean, standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’ of iris.csv dataset. Provide the codes with outputs and explain everything that you do in this step.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\LOQ\\Downloads\\Iris.csv")

In [3]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1.0,5.1,3.5,1.4,0.2,Iris-setosa
1,2.0,4.9,3.0,1.4,0.2,Iris-setosa
2,NaN,4.7,3.2,1.3,0.2,Iris-setosa
3,NaN,4.6,3.1,1.5,0.2,Iris-setosa
4,NaN,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,3.0,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,5.0,1.9,Iris-virginica
147,148.0,6.5,3.0,5.2,2.0,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,3.0,5.1,1.8,Iris-virginica

1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for a dataset (age, income etc.) with numeric variables grouped by one of the qualitative (categorical) variable. For example, if your categorical variable is age groups and quantitative variable is income, then provide summary statistics of income grouped by the age groups. Create a list that contains a numeric value for each response to the categorical variable.

In [4]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  144.000000     150.000000    150.000000     150.000000    150.000000
mean    78.416667       5.843333      3.054000       3.758667      1.198667
std     41.861827       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     42.750000       5.100000      2.800000       1.600000      0.300000
50%     78.500000       5.800000      3.000000       4.350000      1.300000
75%    114.250000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [8]:
df["SepalLengthCm"].describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: SepalLengthCm, dtype: float64

In [10]:
df.groupby("Species").describe()

                   Id                                                       \
                count        mean        std    min     25%    50%     75%
Species
Iris-setosa      44.0   28.227273  13.353623    1.0   17.75   28.5   39.25
Iris-versicolor  50.0   75.500000  14.577380   51.0   63.25   75.5   87.75
Iris-virginica   50.0  125.500000  14.577380  101.0  113.25  125.5  137.75

                       SepalLengthCm         ... PetalLengthCm       \
                   max         count   mean  ...           75%  max
Species                                      ...
Iris-setosa       50.0          50.0  5.006  ...         1.575  1.9
Iris-versicolor  100.0          50.0  5.936  ...         4.600  5.1
Iris-virginica   150.0          50.0  6.588  ...         5.875  6.9

                PetalWidthCm
                       count   mean       std  min  25%  50%  75%  max
Species
Iris-setosa             50.0  0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor         50.0  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica          50.0  2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [11]:
df.groupby("Species").describe().sum()

Id             count    144.000000
               mean     229.227273
               std       42.508382
               min      153.000000
               25%      194.250000
               50%      229.500000
               75%      264.750000
               max      300.000000
SepalLengthCm  count    150.000000
               mean      17.530000
               std        1.504540
               min       14.100000
               25%       16.625000
               50%       17.400000
               75%       18.400000
               max       20.700000
SepalWidthCm   count    150.000000
               mean       9.162000
               std        1.017319
               min        6.500000
               25%        8.450000
               50%        9.200000
               75%        9.850000
               max       11.600000
PetalLengthCm  count    150.000000
               mean      11.276000
               std        1.195317
               min        8.500000
               25%       10.500000
               50%       11.400000
               75%       12.050000
               max       13.900000
PetalWidthCm   count    150.000000
               mean       3.596000
               std        0.579612
               min        2.500000
               25%        3.200000
               50%        3.500000
               75%        4.100000
               max        4.900000
dtype: float64

2. Write a Python program to display some basic statistical details like percentile, mean, standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’ of iris.csv dataset. Provide the codes with outputs and explain everything that you do in this step.

In [12]:
df.groupby("

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  144.000000     150.000000    150.000000     150.000000    150.000000
mean    78.416667       5.843333      3.054000       3.758667      1.198667
std     41.861827       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     42.750000       5.100000      2.800000       1.600000      0.300000
50%     78.500000       5.800000      3.000000       4.350000      1.300000
75%    114.250000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000